[project]
name = "mcp-server"
version = "0.3.4"
description = "GPT-RAG MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "mcp[cli]>=1.21.0",
    "wikipedia>=1.4.0",
]
